### ISSUE TITLE
Executar o projeto

### ISSUE THREAD

**Issue by ghost** [LuizLobao/Whatsapp_Desktop_bot#3]
Olá! Queria saber como posso está executando seu projeto em minha máquina. 
Agradeço desde já!

**Comment by LuizLobao** [comment]
@RichardSmanhoto, depois de clonar o projeto, você vai precisar fazer o seguinte:
* instalar o pynput (pip install pynput)
* ajustar o caminho do executavel do Whatsapp Desktop no [whatsapp_desk_bot.py](https://github.com/LuizLobao/Whatsapp_Desktop_bot/blob/master/whatsapp_desk_bot.py).

`def OpenWhatsappDesktop():
    """Open the Whastapp desktop application. Change the path before use."""
    try:
        os.startfile(r'C:\Users\luiz\AppData\Local\WhatsApp\WhatsApp.exe')
    except Exception as e:
        print(e)`
No arquivo [JSON](https://github.com/LuizLobao/Whatsapp_Desktop_bot/blob/master/lista_mensagens.json) alterar incluindo o nome do seu grupo de WhatsApp e a mensagem desejada.

Executar o [whatsapp_desk_bot.py](https://github.com/LuizLobao/Whatsapp_Desktop_bot/blob/master/whatsapp_desk_bot.py)
